### ISSUE TITLE
Buildout in www jail fails

### ISSUE THREAD

**Issue by seankelly** [buildbot/buildbot-infra#207]
The buildout fails:

```
TASK [simple-buildout : Perform build] *****************************************
 [WARNING]: Using world-readable permissions for temporary files Ansible needs
to create when becoming an unprivileged user. This may be insecure. For
information on securing this, see https://docs.ansible.com/ansible/become.html
#becoming-an-unprivileged-user
changed: [localhost] => (item=npm install)
failed: [localhost] (item=npm run compile) => {"changed": true, "cmd": ["npm", "run", "compile"], "delta": "0:00:00.807462", "end": "2018-11-17 19:39:33.888076", "item": "npm run compile", "msg": "non-zero return code", "rc": 1, "start": "2018-11-17 19:39:33.080614", "stderr": "/usr/home/bbuser/site/node_modules/node-sass/lib/index.js:12\n    throw new Error(errors.unsupportedEnvironment());\n    ^\n\nError: Node Sass does not yet support your current environment: FreeBSD 64-bit with Unsupported runtime (59)\nFor more information on which environments are supported please see:\nhttps://github.com/sass/node-sass/releases/tag/v3.7.0\n    at Object.<anonymous> (/usr/home/bbuser/site/node_modules/node-sass/lib/index.js:12:11)\n    at Module._compile (module.js:660:30)\n    at Object.Module._extensions..js (module.js:671:10)\n    at Module.load (module.js:573:32)\n    at tryModuleLoad (module.js:513:12)\n    at Function.Module._load (module.js:505:3)\n    at Module.require (modul!
 e.js:604:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/usr/home/bbuser/site/node_modules/terraform/lib/stylesheet/processors/scss.js:1:74)\n    at Module._compile (module.js:660:30)\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno 1\nnpm ERR! @ compile: `harp compile src dist`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @ compile script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/bbuser/.npm/_logs/2018-11-17T19_39_33_883Z-debug.log", "stderr_lines": ["/usr/home/bbuser/site/node_modules/node-sass/lib/index.js:12", "    throw new Error(errors.unsupportedEnvironment());", "    ^", "", "Error: Node Sass does not yet support your current environment: FreeBSD 64-bit with Unsupported runtime (59)", "For more information on which environments are supported please see:", "https://github.com/sass/node-sass/releases/!
 tag/v3.7.0", "    at Object.<anonymous> (/usr/home/bbuser/site!
 /node_modules/node-sass/lib/index.js:12:11)", "    at Module._compile (module.js:660:30)", "    at Object.Module._extensions..js (module.js:671:10)", "    at Module.load (module.js:573:32)", "    at tryModuleLoad (module.js:513:12)", "    at Function.Module._load (module.js:505:3)", "    at Module.require (module.js:604:17)", "    at require (internal/module.js:11:18)", "    at Object.<anonymous> (/usr/home/bbuser/site/node_modules/terraform/lib/stylesheet/processors/scss.js:1:74)", "    at Module._compile (module.js:660:30)", "npm ERR! code ELIFECYCLE", "npm ERR! errno 1", "npm ERR! @ compile: `harp compile src dist`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the @ compile script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /home/bbuser/.npm/_logs/2018-11-17T19_39_33_883Z-debug.log"], "stdout": "\n> @ compile /usr/home/bbus!
 er/site\n> harp compile src dist", "stdout_lines": ["", "> @ compile /usr/home/bbuser/site", "> harp compile src dist"]}
...ignoring
```

I think the only failure is Sass not supporting FreeBSD.

**Comment by seankelly** [comment]
There are two errors when installing node-sass:

```In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
```

```In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
         ^
```

The latter is in libsass but the install of node-sass isn't picking up {{/usr/local/include}} as an include location.

**Comment by seankelly** [comment]
Trying with yarn gets farther, I think, but the compile step still fails.

```
[bbuser@www /usr/home/bbuser/site]$ yarn run compile
yarn run v1.10.1
warning package.json: No license field
$ harp compile src dist
node[84390]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x834820 node::Abort(void) [/usr/local/bin/node]
 2: 0x833689 node::Assert(char const* const[4]*) [/usr/local/bin/node]
 3: 0x85929a node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<node::contextify::ContextifyScript::New::Value> const&) [/usr/local/bin/node]
 4: 0xa14113 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0xa135e6 v8::internal::Isolate*<v8::internal::Object> v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::HeapObject>(int, v8::internal::Object*, v8::internal::HeapObject) [/usr/local/bin/node]
 6: 0xa1301b v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
error Command failed with signal "SIGABRT".
```
Version information. All versions are the latest in upstream repository. Upgrading to FreeBSD 11 might get some of them to be newer but not much.
```
[bbuser@www /usr/home/bbuser/site]$ npm --version
6.4.1
[bbuser@www /usr/home/bbuser/site]$ node --version
v10.12.0
[bbuser@www /usr/home/bbuser/site]$ yarn --version
1.10.1
```

**Comment by tardyp** [comment]
did you try to just remove the node_modules dir?

**Comment by seankelly** [comment]
Yeah, that was the second thing I tried after `npm rebuild node-sass`.

**Comment by tardyp** [comment]
I updated the yarn.lock and now it is working

**Comment by seankelly** [comment]
Now I see failures about harp missing.

> failed: [localhost] (item=npm run compile) => {"changed": true, "cmd": ["npm", "run", "compile"], "delta": "0:00:00.409357", "end": "2018-12-18 14:34:42.149708", "item": "npm run compile", "msg": "non-zero return code", "rc": 1, "start": "2018-12-18 14:34:41.740351", "stderr": "harp: not found\nnpm ERR! file sh\nnpm ERR! code ELIFECYCLE\nnpm ERR! errno ENOENT\nnpm ERR! syscall spawn\nnpm ERR! @ compile: `harp compile src dist`\nnpm ERR! spawn ENOENT\nnpm ERR! \nnpm ERR! Failed at the @ compile script.\nnpm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/bbuser/.npm/_logs/2018-12-18T14_34_42_143Z-debug.log", "stderr_lines": ["harp: not found", "npm ERR! file sh", "npm ERR! code ELIFECYCLE", "npm ERR! errno ENOENT", "npm ERR! syscall spawn", "npm ERR! @ compile: `harp compile src dist`", "npm ERR! spawn ENOENT", "npm ERR! ", "npm ERR! Failed at the @ compile script.", "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.", "", "npm ERR! A complete log of this run can be found in:", "npm ERR!     /home/bbuser/.npm/_logs/2018-12-18T14_34_42_143Z-debug.log"], "stdout": "\n> @ compile /usr/home/bbuser/site\n> harp compile src dist", "stdout_lines": ["", "> @ compile /usr/home/bbuser/site", "> harp compile src dist"]}
